# (C) Copyright IBM Deutschland GmbH 2021, 2023
# (C) Copyright IBM Corp. 2021, 2023
#
# non-exclusively licensed to gematik GmbH

########################################################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vau-hsm-simulator-1
  namespace: %NAMESPACE%
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vau-hsm-simulator-1
      serverpod: vau-hsm-simulator-1
  template:
    metadata:
      labels:
        app: vau-hsm-simulator-1
        serverpod: vau-hsm-simulator-1
    spec:
      imagePullSecrets:
        - name: %IMAGE_PULL_SECRET%
      containers:
        - name: vau-hsm-simulator-1
          image: %ICR_INSTANCE%/%ICR_NAMESPACE%/vau-hsm:%VERSION%
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
              name: sdk-port

########################################################################################################################
