# (C) Copyright IBM Deutschland GmbH 2021, 2024
# (C) Copyright IBM Corp. 2021, 2024
#
# non-exclusively licensed to gematik GmbH

########################################################################################################################

apiVersion: v1
kind: Service
metadata:
  labels:
    app: vau-hsm-simulator-2
  name: vau-hsm-simulator-2
  namespace: %NAMESPACE%
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: vau-hsm-simulator-2
  type: ClusterIP

########################################################################################################################
