# (C) Copyright IBM Deutschland GmbH 2021
# (C) Copyright IBM Corp. 2021
# SPDX-License-Identifier: CC BY-NC-ND 3.0 DE

########################################################################################################################

apiVersion: v1
kind: Service
metadata:
  labels:
    app: vau-hsm-simulator-2
  name: vau-hsm-simulator-2
  namespace: %NAMESPACE%
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: vau-hsm-simulator-2
  type: ClusterIP

########################################################################################################################
